#!/bin/sh

# personalize github codespaces
# https://github.com/settings/codespaces
# https://docs.github.com/en/codespaces/customizing-your-codespace/personalizing-codespaces-for-your-account#dotfiles
#
# devcontainer: /workspaces/.codespaces/.persistedshare/dotfiles

# Git
./git-setup.sh

# Copy dotfiles
cp ../.vimrc ~/.vimrc
cp ../.zshrc ~/.zshrc
cp ../.tmux.conf ~/.tmux.conf
cp ../.procs.toml ~/.procs.toml